name: causality
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.6
- jupyter
- jupyterlab
- jupyter_contrib_nbextensions
- matplotlib
- numpy
- pandas
- seaborn
- statsmodels
- networkx
- pytest
